/**
 * Derives the app's shipping imagery from the original design exports.
 *
 *   assets/*.png   →   src/assets/*.jpg  +  src/assets/lqip.js
 *   (source of truth)  (what Vite bundles)
 *
 * The originals are 4.3 MB of lossless PNG — correct for an archive, ruinous
 * for a hero image. This emits a responsive pair of JPEGs per photo plus a
 * ~20px LQIP thumbnail, inlined as a data URI, that `Figure` shows blurred
 * behind the real image until it decodes.
 *
 *   node scripts/build-images.mjs
 *
 * Uses macOS `sips`, so it only runs on a Mac. The outputs are committed, so
 * this only needs re-running when the source photography changes.
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE_DIR = resolve(ROOT, "assets");
const OUT_DIR = resolve(ROOT, "src/assets");
const TMP_DIR = resolve(OUT_DIR, ".tmp");

/**
 * `quality` is tuned per image to what its treatment can hide: the hero sits
 * under a heavy scrim and a glass panel, so it tolerates more compression
 * than the about photos, which are shown clean.
 */
const PHOTOS = [
  { name: "hero-steel", key: "hero", widths: [1400, 760], quality: 72 },
  { name: "about-main", key: "aboutMain", widths: [900, 600], quality: 78 },
  { name: "about-inset", key: "aboutInset", widths: [500], quality: 78 },
];

const LQIP_WIDTH = 20;
const LQIP_QUALITY = 40;

function sips(args) {
  execFileSync("sips", args, { stdio: ["ignore", "ignore", "pipe"] });
}

/** Ask sips for an image's real pixel dimensions. */
function dimensionsOf(file) {
  const out = execFileSync("sips", ["-g", "pixelWidth", "-g", "pixelHeight", file], {
    encoding: "utf8",
  });
  const width = Number(out.match(/pixelWidth:\s*(\d+)/)?.[1]);
  const height = Number(out.match(/pixelHeight:\s*(\d+)/)?.[1]);
  return { width, height };
}

mkdirSync(OUT_DIR, { recursive: true });
mkdirSync(TMP_DIR, { recursive: true });

const lqip = {};
const manifest = [];

for (const photo of PHOTOS) {
  const source = resolve(SOURCE_DIR, `${photo.name}.png`);
  const { width: srcWidth, height: srcHeight } = dimensionsOf(source);

  for (const width of photo.widths) {
    const out = resolve(OUT_DIR, `${photo.name}-${width}.jpg`);
    // -Z bounds the longest edge; our sources are all landscape or square,
    // so that is the width in every case here.
    sips([
      "-s", "format", "jpeg",
      "-s", "formatOptions", String(photo.quality),
      "-Z", String(width),
      source,
      "--out", out,
    ]);
    manifest.push({ file: `${photo.name}-${width}.jpg`, bytes: readFileSync(out).length });
  }

  // LQIP — deliberately tiny. Figure blurs it up to full size, so detail here
  // would only cost bytes.
  const thumb = resolve(TMP_DIR, `${photo.name}.jpg`);
  sips([
    "-s", "format", "jpeg",
    "-s", "formatOptions", String(LQIP_QUALITY),
    "-Z", String(LQIP_WIDTH),
    source,
    "--out", thumb,
  ]);
  lqip[photo.key] = `data:image/jpeg;base64,${readFileSync(thumb).toString("base64")}`;

  console.log(
    `${photo.name}  ${srcWidth}×${srcHeight}  →  ${photo.widths.join("w, ")}w` +
      `  · lqip ${lqip[photo.key].length} chars`,
  );
}

rmSync(TMP_DIR, { recursive: true, force: true });

const entries = Object.entries(lqip)
  .map(([key, uri]) => `  ${key}:\n    "${uri}",`)
  .join("\n");

writeFileSync(
  resolve(OUT_DIR, "lqip.js"),
  `/**
 * GENERATED by scripts/build-images.mjs — do not edit by hand.
 *
 * ${LQIP_WIDTH}px-wide JPEG thumbnails as data URIs. \`Figure\` paints one,
 * scaled up and blurred, behind each photo so the frame is filled with the
 * image's own colours from the first paint instead of an empty box.
 */
export const LQIP = {
${entries}
};
`,
);

const total = manifest.reduce((sum, item) => sum + item.bytes, 0);
console.log(`\n${manifest.length} files, ${(total / 1024).toFixed(0)} KB total`);
for (const item of manifest) {
  console.log(`  ${item.file.padEnd(24)} ${(item.bytes / 1024).toFixed(0)} KB`);
}
